name: AstroEffects
version: 1.0
main: com.astronetwork.effects.Effects
authors: [JustNiico, Lexuss]
commands:
	speed:
		description: Get speed for 5 minutes.
		aliases: spd
	strength:
		description: Get strength for 5 minutes.
		aliases: str
	invisibility:
	    description: Get invisibility for 5 minutes.