name: AstroEffects
version: 1.1
main: com.astronetwork.effects.Effects
authors: [JustNiico, Lexuss]
commands:
	speed:
		description: Get speed for 5 minutes.
	strength:
		description: Get strength for 5 minutes.
	invis:
	    description: Get invisibility for 5 minutes.
	haste:
	 	description: Get haste for 5 minutes.
	regen:
		description: Get regeneration for 5 minutes.
	jump:
		description: Get jump boost for 5 minutes.
	nv:
		description: Get night vision for 5 minutes.
	waterbreath:
		description: Get water breathing for 5 minutes.